### PR TITLE
bump deps for snyk vulnerability

### PR DESCRIPTION
**Pull request by gabe0x02**
Bump some deps for snyk vulnerability.

### CODE REVIEW

**Review by gairal — APPROVED** [review]

**Review by jeffwesson — APPROVED** [review]
I don't believe this is actually used anywhere but I fully support this

**Comment by hanrebecca** [comment]
Hi can y’all unsubscribe me from this please? I don’t know my log-in and am too lazy to figure it out.

Thank you!

Please disregard any typos as this was sent from my iPhone

**Comment by jeffwesson** [comment]
👋  @hanrebecca - hope you're well, we'll remove you. Cheers!

**Comment by hanrebecca** [comment]
/unsubscribe

Please disregard any typos as this was sent from my iPhone

**Pull request closed without merging**
